channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=25.0.1
- pip:
  - mlflow==2.20.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==6.1.0
  - scikit-learn==1.3.2
  - scipy==1.14.0
name: mlflow-env
